#############################################################################
# Makefile for building: VitalCoin-qt
# Generated by qmake (2.01a) (Qt 4.8.5) on: ?? 2? 3 22:29:32 2018
# Project:  VitalCoin-qt.pro
# Template: app
# Command: d:/mkcoin/Qt/qt4.8.5/bin/qmake.exe BOOST_INCLUDE_PATH=D:\mkcoin\libs/boost_1_55_0 BOOST_LIB_PATH=D:\mkcoin\libs/boost_1_55_0/stage/lib BOOST_LIB_SUFFIX=-mgw48-mt-1_55 OPENSSL_INCLUDE_PATH=D:\mkcoin\libs/openssl-1.0.1g/include OPENSSL_LIB_PATH=D:\mkcoin\libs/openssl-1.0.1g BDB_INCLUDE_PATH=D:\mkcoin\libs/db-4.8.30.NC/build_unix BDB_LIB_PATH=D:\mkcoin\libs/db-4.8.30.NC/build_unix MINIUPNPC_INCLUDE_PATH=D:\mkcoin\libs/miniupnpc-1.9 MINIUPNPC_LIB_PATH=D:\mkcoin\libs/miniupnpc-1.9 QRENCODE_INCLUDE_PATH=D:\mkcoin\libs/qrencode-3.4.3-mgw QRENCODE_LIB_PATH=D:\mkcoin\libs/qrencode-3.4.3-mgw/.libs "QMAKE_CXXFLAGS=-fno-guess-branch-probability -frandom-seed=1984 -Wno-unused-variable -Wno-unused-value -Wno-sign-compare -Wno-strict-aliasing" "QMAKE_CFLAGS=-fno-guess-branch-probability -frandom-seed=1984 -Wno-unused-variable -Wno-unused-value -Wno-sign-compare -Wno-strict-aliasing" -o Makefile VitalCoin-qt.pro
#############################################################################

first: debug
install: debug-install
uninstall: debug-uninstall
MAKEFILE      = Makefile
QMAKE         = d:/mkcoin/Qt/qt4.8.5/bin/qmake.exe
DEL_FILE      = rm
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp
COPY_FILE     = $(COPY)
COPY_DIR      = cp -r
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		debug \
		release

debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: VitalCoin-qt.pro  ../Qt/qt4.8.5/mkspecs/default/qmake.conf ../Qt/qt4.8.5/mkspecs/features/device_config.prf \
		../Qt/qt4.8.5/mkspecs/qconfig.pri \
		../Qt/qt4.8.5/mkspecs/features/qt_functions.prf \
		../Qt/qt4.8.5/mkspecs/features/qt_config.prf \
		../Qt/qt4.8.5/mkspecs/win32-g++/qmake.conf \
		../Qt/qt4.8.5/mkspecs/features/exclusive_builds.prf \
		../Qt/qt4.8.5/mkspecs/features/default_pre.prf \
		../Qt/qt4.8.5/mkspecs/features/win32/default_pre.prf \
		../Qt/qt4.8.5/mkspecs/features/debug.prf \
		../Qt/qt4.8.5/mkspecs/features/debug_and_release.prf \
		../Qt/qt4.8.5/mkspecs/features/default_post.prf \
		../Qt/qt4.8.5/mkspecs/features/win32/default_post.prf \
		../Qt/qt4.8.5/mkspecs/features/static.prf \
		../Qt/qt4.8.5/mkspecs/features/win32/rtti.prf \
		../Qt/qt4.8.5/mkspecs/features/win32/exceptions.prf \
		../Qt/qt4.8.5/mkspecs/features/win32/stl.prf \
		../Qt/qt4.8.5/mkspecs/features/warn_on.prf \
		../Qt/qt4.8.5/mkspecs/features/qt.prf \
		../Qt/qt4.8.5/mkspecs/features/win32/thread.prf \
		../Qt/qt4.8.5/mkspecs/features/moc.prf \
		../Qt/qt4.8.5/mkspecs/features/win32/windows.prf \
		../Qt/qt4.8.5/mkspecs/features/resources.prf \
		../Qt/qt4.8.5/mkspecs/features/uic.prf \
		../Qt/qt4.8.5/mkspecs/features/yacc.prf \
		../Qt/qt4.8.5/mkspecs/features/lex.prf \
		d:/mkcoin/Qt/qt4.8.5/lib/qtmaind.prl \
		d:/mkcoin/Qt/qt4.8.5/lib/QtGui.prl \
		d:/mkcoin/Qt/qt4.8.5/lib/QtNetwork.prl \
		d:/mkcoin/Qt/qt4.8.5/lib/QtCore.prl
	$(QMAKE) BOOST_INCLUDE_PATH=D:\mkcoin\libs/boost_1_55_0 BOOST_LIB_PATH=D:\mkcoin\libs/boost_1_55_0/stage/lib BOOST_LIB_SUFFIX=-mgw48-mt-1_55 OPENSSL_INCLUDE_PATH=D:\mkcoin\libs/openssl-1.0.1g/include OPENSSL_LIB_PATH=D:\mkcoin\libs/openssl-1.0.1g BDB_INCLUDE_PATH=D:\mkcoin\libs/db-4.8.30.NC/build_unix BDB_LIB_PATH=D:\mkcoin\libs/db-4.8.30.NC/build_unix MINIUPNPC_INCLUDE_PATH=D:\mkcoin\libs/miniupnpc-1.9 MINIUPNPC_LIB_PATH=D:\mkcoin\libs/miniupnpc-1.9 QRENCODE_INCLUDE_PATH=D:\mkcoin\libs/qrencode-3.4.3-mgw QRENCODE_LIB_PATH=D:\mkcoin\libs/qrencode-3.4.3-mgw/.libs "QMAKE_CXXFLAGS=-fno-guess-branch-probability -frandom-seed=1984 -Wno-unused-variable -Wno-unused-value -Wno-sign-compare -Wno-strict-aliasing" "QMAKE_CFLAGS=-fno-guess-branch-probability -frandom-seed=1984 -Wno-unused-variable -Wno-unused-value -Wno-sign-compare -Wno-strict-aliasing" -o Makefile VitalCoin-qt.pro
../Qt/qt4.8.5/mkspecs/features/device_config.prf:
../Qt/qt4.8.5/mkspecs/qconfig.pri:
../Qt/qt4.8.5/mkspecs/features/qt_functions.prf:
../Qt/qt4.8.5/mkspecs/features/qt_config.prf:
../Qt/qt4.8.5/mkspecs/win32-g++/qmake.conf:
../Qt/qt4.8.5/mkspecs/features/exclusive_builds.prf:
../Qt/qt4.8.5/mkspecs/features/default_pre.prf:
../Qt/qt4.8.5/mkspecs/features/win32/default_pre.prf:
../Qt/qt4.8.5/mkspecs/features/debug.prf:
../Qt/qt4.8.5/mkspecs/features/debug_and_release.prf:
../Qt/qt4.8.5/mkspecs/features/default_post.prf:
../Qt/qt4.8.5/mkspecs/features/win32/default_post.prf:
../Qt/qt4.8.5/mkspecs/features/static.prf:
../Qt/qt4.8.5/mkspecs/features/win32/rtti.prf:
../Qt/qt4.8.5/mkspecs/features/win32/exceptions.prf:
../Qt/qt4.8.5/mkspecs/features/win32/stl.prf:
../Qt/qt4.8.5/mkspecs/features/warn_on.prf:
../Qt/qt4.8.5/mkspecs/features/qt.prf:
../Qt/qt4.8.5/mkspecs/features/win32/thread.prf:
../Qt/qt4.8.5/mkspecs/features/moc.prf:
../Qt/qt4.8.5/mkspecs/features/win32/windows.prf:
../Qt/qt4.8.5/mkspecs/features/resources.prf:
../Qt/qt4.8.5/mkspecs/features/uic.prf:
../Qt/qt4.8.5/mkspecs/features/yacc.prf:
../Qt/qt4.8.5/mkspecs/features/lex.prf:
d:\mkcoin\Qt\qt4.8.5\lib\qtmaind.prl:
d:\mkcoin\Qt\qt4.8.5\lib\QtGui.prl:
d:\mkcoin\Qt\qt4.8.5\lib\QtNetwork.prl:
d:\mkcoin\Qt\qt4.8.5\lib\QtCore.prl:
qmake: qmake_all FORCE
	@$(QMAKE) BOOST_INCLUDE_PATH=D:\mkcoin\libs/boost_1_55_0 BOOST_LIB_PATH=D:\mkcoin\libs/boost_1_55_0/stage/lib BOOST_LIB_SUFFIX=-mgw48-mt-1_55 OPENSSL_INCLUDE_PATH=D:\mkcoin\libs/openssl-1.0.1g/include OPENSSL_LIB_PATH=D:\mkcoin\libs/openssl-1.0.1g BDB_INCLUDE_PATH=D:\mkcoin\libs/db-4.8.30.NC/build_unix BDB_LIB_PATH=D:\mkcoin\libs/db-4.8.30.NC/build_unix MINIUPNPC_INCLUDE_PATH=D:\mkcoin\libs/miniupnpc-1.9 MINIUPNPC_LIB_PATH=D:\mkcoin\libs/miniupnpc-1.9 QRENCODE_INCLUDE_PATH=D:\mkcoin\libs/qrencode-3.4.3-mgw QRENCODE_LIB_PATH=D:\mkcoin\libs/qrencode-3.4.3-mgw/.libs "QMAKE_CXXFLAGS=-fno-guess-branch-probability -frandom-seed=1984 -Wno-unused-variable -Wno-unused-value -Wno-sign-compare -Wno-strict-aliasing" "QMAKE_CFLAGS=-fno-guess-branch-probability -frandom-seed=1984 -Wno-unused-variable -Wno-unused-value -Wno-sign-compare -Wno-strict-aliasing" -o Makefile VitalCoin-qt.pro

qmake_all: FORCE

make_default: debug-make_default release-make_default FORCE
make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

check: first

debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
